### ISSUE TITLE
DartFormat: External dart format process is not running. 

### ISSUE THREAD

**Issue by dinoware** [eggnstone/DartFormatVSCodePlugin#1]
![image](https://github.com/user-attachments/assets/d3968885-5ba0-4350-a058-04961c63ca30)

Good morning. I have an issue with launching the extension. I installed dart_format from the instruction, but each time I press ctrl+alt+, - each time I get this warning message and nothing happen. Help me please to solve this, I saw the screenshot of how the extension works and I really want to use it.

**Comment by dinoware** [comment]
I'm using Windows 11, the latest version of VS Code and the latest version of the Dart Format, installed from VS Code Extensions.

**Comment by eggnstone** [comment]
Thanks for the report! Should be fixed with version 0.1.3

**Comment by dinoware** [comment]
So fast! AWESOME! Thank you!

**Comment by eggnstone** [comment]
@dinoware I made more changes and also added buttons for installing/updating dart_format (when dart_format is not installed yet or needs an update).
If everything works fine then could you leave a review on the extension page please?
